# Generated by Django 3.1.4 on 2020-12-08 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20201207_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='postal_address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='user_email',
            field=models.EmailField(blank=True, max_length=255, unique=True),
        ),
    ]
